//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


HELLO_IN_KOREAN = 'an-nyoung-ha-se-yo';
HELLO_IN_FRENCH = 'bonjour!';
HELLO_IN_JAPANESE = 'konichiwa!';
